= Краткое описание функционала

J2DB - сервис для генерации базы данных PostgreSQL, MySQL или MongoDb на основе JSON. Сервис также поддерживает загрузку данных в csv-формате. Взаимодействие с сервисом происходит через API. На вход подается JSON, со структурой данных, на выходе пользователь получает настройки для подключения к базе с соответствующей структурой и сгенерированными данными.

=== API должен предоставлять следующие методы:

- POST /database - создает на сервере базу с указанной схемой, в ответе приходит ID базы
- DELETE /database/{id} - удаляет базу
- GET /database - возвращает список баз на сервере
- POST /generation/database/{id}- заполняет базу случайными данными
- POST /populate/database/{id} - загружает данные в формате csv


=== Входящий JSON должен соответсвовать одной из следующих структур:
- Для PostgreSQL и MySQL
----
        {
        	"type": <string> PostgreSQL/MySQL
        	"name": <string> имя базы
        	"tables": [
        		{
        			"schema": <string> имя схемы
        			"name": <string> имя таблицы
        			"columns": [
        				{ 
        					"name": <string> имя колонки,
        					"type": <string> строка c типом PostgreSQL,
        					"not_null": <boolean>,
        					"primary_key": <boolean>,
        					"rule": <string> не обязательное поле, либо:
        						1. ${dictionary."<имя_словаря_данных>"}
        						2. ${pattern."<регулярное_выражение>"}
        						3. ${constant."<значение>"}
        				},
        				...
        			]
        		}
        	],
        	"foreign_keys": [
        		{
        			"table": <string> имя таблицы, содержащей ключ
        			"name": <string> имя ключа,
        			"column": <string> имя колонки с ключом
        			"references": <string> ссылка в формате <имя_таблицы>(<имя_колонки>)
        		},
        		...
        	],
        	"indexes": [
        		{
        			"name": <string> имя индекса,
        			"references": <string> ссылка в формате <имя_таблицы>(<имя_колонки>)
        		}
        	],
        	"dictionaries": [
        		"name": <string> имя словаря данных,
        		"values": <array> набор значений, соответствующего типа
        	]
        }
----


- Для MongoDb
----
        {
        	"type": <string> MongoDb
        	"collections": [
        		{
        			"name": <string> имя коллекции,
        			"documents": [
        				{	
        					"name": <string> имя поля,
        					"type": <string> тип поля,
        					"rule": <string> не обязательное поле, либо:
        						1. ${dictionary."<имя_словаря_данных>"}
        						2. ${pattern."<регулярное_выражение>"}
        						3. ${constant."<значение>"}
        				},
        				...
        			]
        		}
        		...
        	],
        	"dictionaries": [
        		"name": <string> имя словаря данных,
        		"values": <array> набор обьектов, либо типовых значений
        	]
        }
----

== Замечания:
- В таблице обязательно должен быть первичный ключ
- Метод POST POST /database добавляет в таблицу DATABASE запись для созданной базы, со статусом CREATED
- Методы POST POST /data/generation/database/{id} и /data/populate/database/{id} могут работать только с базой в статусе CREATED, иначе возвращают ошибку. После окончания работые переводит базу в статус POPULATED
- При генерации данных, значения для внешних ключей выбираются случайно из списка допустимых значений
- Порядок создания таблиц основывается на внешних ключах
- Сервисы валидации не имеют публичного API. Работают с асинхронными запросами из других сервисов.